name: Test Docker Actions

on:
    pull_request: 
        types: 
            - opened
        branches:
            - main
            - '!feature/*'

jobs:
    testing-action:
        name: Testing Docker Action
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: Post PR Comment
              uses: ifeanyi23/ifeanyi23-docker-action-pr-giphy-comment@main
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                giphy-api-key: ${{secrets.GIPHY_API_KEY}}